# automatically calc. count of threads
autoThreads=true
# manual setup if autoThreads=false
# for HDD max is 2 for all actions
# for SDD max is 6 to read, 4 to write/delete
threadCountScan=2
threadCountCopy=1
threadCountDelete=1
# compare by LastModified file param
compareByLastModified=false
# serialization table values
copyFiles=copyFiles.ser
duplicateFiles=duplicateFiles.ser
workSessionArchFolder=work_table_arch